language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
    php: nightly

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit